packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma
  - esbuild
  - sharp
  - unrs-resolver
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
